### ISSUE TITLE
How to use with Next.js and CSS modules?

### ISSUE THREAD

**Issue by th0th** [jonathantneal/postcss-focus-ring#12]
Hi, first of all, thanks for the package 💐 

I am trying to use this plugin with Next.js and [focus-within polyfill](https://github.com/WICG/focus-visible). In this case the plugin works only when I use it like this:

```css
div.class:global(:focus-within) {
  background-color: red;
}
```

but not without `:global`:

```css
div.class:focus-within {
  background-color: red;
}
```

I couldn't find a configuration option about CSS modules, `:local` and `:global` stuff in the documentation. Am I doing something wrong or is there a workaround?
